version: '3.8'

services:

  # MySql
  dbLocal:
    image: mysql:8.0
    container_name: dbMySQL
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=db_local
      - MYSQL_ROOT_PASSWORD=secretPassword
    ports:
      - '3306:3306'
    volumes:
      - dbVol:/var/lib/mysql
      - ./dbVol/init.sql:/docker-entrypoint-initdb.d/init.sql
    # deploy:
    #   resources:
    #     limits:
    #       memory: 500M
  
  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - dbLocal
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    environment:
      PMA_HOST: dbLocal
      MYSQL_ROOT_PASSWORD: secretPassword
    ports:
      - 8090:80
    restart: unless-stopped

volumes:
  dbVol:
    driver: local

