version: '2'

services:

  # MySql
  mysqlDB:
    image: "mysql:5.7"
    container_name: container_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=secretPassword
    volumes:
      - ./datadir/:/var/lib/mysql
    ports:
      - "3306:3306"
  
  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - mysqlDB
    image: phpmyadmin/phpmyadmin
    container_name: container_phpMyAdmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysqlDB
      MYSQL_ROOT_PASSWORD: secretPassword

